global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 15s
    scrape_timeout: 15s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - localhost:9090

  - job_name: "dse"
    scrape_interval: 15s
    scrape_timeout:  15s
    honor_labels: true
    file_sd_configs:
      - files:
        - 'tg_dse.json'
    metric_relabel_configs:
     - source_labels: [__name__]
       regex: .*rate_(mean|1m|5m|15m)
       action: drop
     #save the original name for all metrics
     - source_labels: [__name__]
       regex: (collectd_dse_.+)
       target_label: prom_name
       replacement: ${1}
     - source_labels: ["prom_name"]
       regex: .+_histogram_p(\d+)
       target_label: quantile
       replacement: .${1}
     - source_labels: ["prom_name"]
       regex: .+_bucket_(\d+)
       target_label: le
       replacement: ${1}
     - source_labels: ["prom_name"]
       regex: .+_bucket_inf
       target_label: le
       replacement: +Inf
     #Table Metrics *ALL* we can drop
     - source_labels: ["dse"]
       regex: org.apache.cassandra.metrics.table.([^\.]+)
       action: drop
     #Table Metrics
     - source_labels: ["dse"]
       regex: org.apache.cassandra.metrics.table.([^\.]+).([^\.]+).([^\.]+)
       target_label: table
       replacement: ${3}
     - source_labels: ["dse"]
       regex: org.apache.cassandra.metrics.table.([^\.]+).([^\.]+).([^\.]+)
       target_label: keyspace
       replacement: ${2}
     - source_labels: ["dse"]
       regex: org.apache.cassandra.metrics.table.([^\.]+).([^\.]+).([^\.]+)
       target_label: __name__
       replacement: dse_table_${1}
     #Keyspace Metrics
     - source_labels: ["dse"]
       regex: org.apache.cassandra.metrics.keyspace.([^\.]+).([^\.]+)
       target_label: keyspace
       replacement: ${2}
     - source_labels: ["dse"]
       regex: org.apache.cassandra.metrics.keyspace.([^\.]+).([^\.]+)
       target_label: __name__
       replacement: dse_keyspace_${1}
     #ThreadPool Metrics
     - source_labels: ["dse"]
       regex: org.apache.cassandra.metrics.thread_pools.([^\.]+).([^\.]+).([^\.]+)
       target_label: pool_type
       replacement: ${2}
     - source_labels: ["dse"]
       regex: org.apache.cassandra.metrics.thread_pools.([^\.]+).([^\.]+).([^\.]+)
       target_label: pool_name
       replacement: ${3}
     - source_labels: ["dse"]
       regex: org.apache.cassandra.metrics.thread_pools.([^\.]+).([^\.]+).([^\.]+)
       target_label: __name__
       replacement: dse_thread_pools_${1}
     #ClientRequest Metrics
     - source_labels: ["dse"]
       regex: org.apache.cassandra.metrics.client_request.([^\.]+).([^\.]+)
       target_label: request_type
       replacement: ${2}
     - source_labels: ["dse"]
       regex: org.apache.cassandra.metrics.client_request.([^\.]+).([^\.]+)
       target_label: __name__
       replacement: dse_client_request_${1}
     #Cache Metrics
     - source_labels: ["dse"]
       regex: org.apache.cassandra.metrics.cache.([^\.]+).([^\.]+)
       target_label: cache_name
       replacement: ${2}
     - source_labels: ["dse"]
       regex: org.apache.cassandra.metrics.cache.([^\.]+).([^\.]+)
       target_label: __name__
       replacement: dse_cache_${1}
     #CQL Metrics
     - source_labels: ["dse"]
       regex: org.apache.cassandra.metrics.cql.([^\.]+)
       target_label: __name__
       replacement: dse_cql_${1}
     #Dropped Message Metrics
     - source_labels: ["dse"]
       regex: org.apache.cassandra.metrics.dropped_messages.([^\.]+).([^\.]+)
       target_label: message_type
       replacement: ${2}
     - source_labels: ["dse"]
       regex: org.apache.cassandra.metrics.dropped_messages.([^\.]+).([^\.]+)
       target_label: __name__
       replacement: dse_dropped_messages_${1}
     #Streaming Metrics
     - source_labels: ["dse"]
       regex: org.apache.cassandra.metrics.streaming.([^\.]+).(.+)
       target_label: peer_ip
       replacement: ${2}
     - source_labels: ["dse"]
       regex: org.apache.cassandra.metrics.cache.([^\.]+).(.+)
       target_label: __name__
       replacement: dse_streaming_${1}
     #CommitLog Metrics
     - source_labels: ["dse"]
       regex: org.apache.cassandra.metrics.commit_log.([^\.]+)
       target_label: __name__
       replacement: dse_commit_log_${1}
     #Compaction Metrics
     - source_labels: ["dse"]
       regex: org.apache.cassandra.metrics.compaction.([^\.]+)
       target_label: __name__
       replacement: dse_compaction_${1}
     #Storage Metrics
     - source_labels: ["dse"]
       regex: org.apache.cassandra.metrics.storage.([^\.]+)
       target_label: __name__
       replacement: dse_storage_${1}
     #Batch Metrics
     - source_labels: ["dse"]
       regex: org.apache.cassandra.metrics.batch.([^\.]+)
       target_label: __name__
       replacement: dse_batch_${1}
     #Client Metrics
     - source_labels: ["dse"]
       regex: org.apache.cassandra.metrics.client.([^\.]+)
       target_label: __name__
       replacement: dse_client_${1}
     #BufferPool Metrics
     - source_labels: ["dse"]
       regex: org.apache.cassandra.metrics.buffer_pool.([^\.]+)
       target_label: __name__
       replacement: dse_buffer_pool_${1}
     #Index Metrics
     - source_labels: ["dse"]
       regex: org.apache.cassandra.metrics.index.([^\.]+)
       target_label: __name__
       replacement: dse_sstable_index_${1}
     #HintService Metrics
     - source_labels: ["dse"]
       regex: org.apache.cassandra.metrics.hinted_hand_off_manager.([^\-]+)-([^\.]+)
       target_label: peer_ip
       replacement: ${2}
     - source_labels: ["dse"]
       regex: org.apache.cassandra.metrics.hinted_hand_off_manager.([^\-]+)-([^\.]+)
       target_label: __name__
       replacement: dse_hints_${1}
     #HintService Metrics
     - source_labels: ["dse"]
       regex: org.apache.cassandra.metrics.hints_service.hints_delays-([^\.]+)
       target_label: peer_ip
       replacement: ${1}
     - source_labels: ["dse"]
       regex: org.apache.cassandra.metrics.hints_service.hints_delays-([^\.]+)
       target_label: __name__
       replacement: dse_hints_hints_delays
     - source_labels: ["dse"]
       regex: org.apache.cassandra.metrics.hints_service.([^\-]+)
       target_label: __name__
       replacement: dse_hints_${1}
     #Dropped Message Metrics
     - source_labels: ["dse"]
       regex: org.apache.cassandra.metrics.dropped_messages.([^\.]+).([^\.]+)
       target_label: message_type
       replacement: ${2}
     - source_labels: ["dse"]
       regex: org.apache.cassandra.metrics.dropped_messages.([^\.]+).([^\.]+)
       target_label: __name__
       replacement: dse_dropped_messages_${1}
     #NodeSync Metrics
     - source_labels: ["dse"]
       regex: com.datastax.nodesync.node_sync_metrics.([^\.]+)
       target_label: __name__
       replacement: dse_node_sync_${1}
     #ContinuousPaging Metrics
     - source_labels: ["dse"]
       regex: org.apache.cassandra.metrics.continuous_paging.([^\.]+)
       target_label: __name__
       replacement: dse_continuous_paging_${1}
     #GC Metrics
     - source_labels: ["dse"]
       regex: jvm.gc.([^\.]+).([^\.]+)
       target_label: collector_type
       replacement: ${1}
     - source_labels: ["dse"]
       regex: jvm.gc.([^\.]+).([^\.]+)
       target_label: __name__
       replacement: dse_jvm_gc_${2}
     #JVM Metrics
     - source_labels: ["dse"]
       regex: jvm.memory.([^\.]+).([^\.]+)
       target_label: memory_type
       replacement: ${1}
     - source_labels: ["dse"]
       regex: jvm.memory.([^\.]+).([^\.]+)
       target_label: __name__
       replacement: dse_jvm_memory_${2}
     - source_labels: ["dse"]
       regex: jvm.memory.pools.([^\.]+).([^\.]+)
       target_label: pool_name
       replacement: ${2}
     - source_labels: ["dse"]
       regex: jvm.memory.pools.([^\.]+).([^\.]+)
       target_label: __name__
       replacement: dse_jvm_memory_pool_${2}
     - source_labels: ["dse"]
       regex: jvm.fd.usage
       target_label: __name__
       replacement: dse_jvm_fd_usage
     - source_labels: ["dse"]
       regex: jvm.buffers.([^\.]+).([^\.]+)
       target_label: buffer_type
       replacement: ${1}
     - source_labels: ["dse"]
       regex: jvm.buffers.([^\.]+).([^\.]+)
       target_label: __name__
       replacement: dse_jvm_buffer_${2}
     #Append the prom types back to formatted names
     - source_labels: [__name__, "prom_name"]
       regex: (dse_.*);.*(_micros_bucket|_bucket|_micros_count_total|_count_total|_total|_micros_sum|_sum).*
       separator: ;
       target_label: __name__
       replacement: ${1}${2}
     - regex: prom_name
       action: labeldrop
